import React, { useState } from 'react';
import { Header } from './components/Header';
import { Dashboard } from './components/Dashboard';
import { PackageForm } from './components/PackageForm';
import { Login } from './components/Login';
import { UserManagement } from './components/UserManagement';
import { SalesManagement } from './components/SalesManagement';
import { VoyageList } from './components/VoyageList';
import { OpsDashboard } from './components/OpsDashboard';
import { OpsManager } from './components/OpsManager';
import { PackageState, OpsDepartureGroup, Booking } from './types';
import { useUserStore } from './store/useUserStore';
import { usePackageStore } from './store/usePackageStore';
import { useBookingStore } from './store/useBookingStore';

export default function App() {
  // --- Stores ---
  const { currentUser, login, logout } = useUserStore();
  const { addPackage, updatePackage } = usePackageStore();
  const { addBooking } = useBookingStore();
  const { updatePackageStock, packages } = usePackageStore(); // Needed for booking logic check

  // --- UI State ---
  const [currentView, setCurrentView] = useState<'dashboard' | 'form' | 'users' | 'sales' | 'voyages' | 'ops'>('dashboard');
  const [editingPackage, setEditingPackage] = useState<PackageState | null>(null);
  const [selectedOpsGroup, setSelectedOpsGroup] = useState<{pkg: PackageState, group: OpsDepartureGroup} | null>(null);

  // --- Handlers ---
  const handleCreatePackage = () => {
    setEditingPackage(null);
    setCurrentView('form');
  };

  const handleEditPackage = (pkg: PackageState) => {
    setEditingPackage(pkg);
    setCurrentView('form');
  };

  const handleDuplicatePackage = (pkg: PackageState) => {
    const newPkg = {
      ...pkg,
      id: undefined, // Will be generated by store
      general: {
        ...pkg.general,
        productName: `${pkg.general.productName} (Copie)`,
        productCode: `${pkg.general.productCode}-COPY`,
        creationDate: new Date().toLocaleDateString('fr-FR'),
      },
      status: 'draft' as const
    };
    setEditingPackage(newPkg);
    setCurrentView('form');
  };

  const handleSavePackage = (data: PackageState, isDraft: boolean) => {
    const newPackage = {
      ...data,
      id: data.id || `pkg-${Date.now()}`,
      status: isDraft ? 'draft' : 'published',
      lastModified: new Date().toISOString().split('T')[0]
    } as PackageState;

    if (data.id) {
      updatePackage(newPackage);
    } else {
      addPackage(newPackage);
    }
    setCurrentView('dashboard');
  };

  const handleAddBooking = (bookingData: Omit<Booking, 'id' | 'bookingDate' | 'salesAgentId' | 'salesAgentName'>) => {
      // Stock Check
      const pkg = packages.find(p => p.id === bookingData.packageId);
      const totalPax = (bookingData.adultCount || 0) + (bookingData.childCount || 0) + (bookingData.infantCount || 0);
      
      if (pkg && (pkg.general.stock || 0) < totalPax) {
          alert("Erreur: Stock insuffisant !");
          return false;
      }

      const newBooking: Booking = {
          ...bookingData,
          id: `bk-${Date.now()}`,
          bookingDate: new Date().toISOString(),
          salesAgentId: currentUser?.id || 'unknown',
          salesAgentName: currentUser?.fullName || 'Inconnu'
      };

      addBooking(newBooking);
      
      if (pkg?.id) {
          updatePackageStock(pkg.id, totalPax);
      }
      return true;
  };

  // --- Access Control Helpers ---
  const role = currentUser?.role;
  const canCreatePackage = role === 'administrator' || role === 'travel_designer';
  const canEditPackage = role === 'administrator' || role === 'travel_designer';
  const canPublishPackage = role === 'administrator'; 
  const canSaveDraft = role === 'administrator' || role === 'travel_designer';
  const canViewUsers = role === 'administrator';
  const canViewSales = role === 'administrator' || role === 'sales_agent' || role === 'travel_designer';
  const canViewOps = role === 'administrator' || role === 'travel_designer'; 

  // --- Render ---
  if (!currentUser) {
    return <Login onLogin={login} />;
  }

  return (
    <div className="min-h-screen bg-background-light dark:bg-background-dark flex flex-col font-display">
      <Header 
        user={currentUser} 
        currentView={currentView}
        onNavigateHome={() => setCurrentView('dashboard')}
        onNavigateUsers={canViewUsers ? () => setCurrentView('users') : undefined}
        onNavigateSales={canViewSales ? () => setCurrentView('sales') : undefined}
        onNavigateVoyages={() => setCurrentView('voyages')}
        onNavigateOps={canViewOps ? () => { setCurrentView('ops'); setSelectedOpsGroup(null); } : undefined}
        onLogout={logout}
      />

      <main className="flex-1 flex flex-col relative overflow-hidden">
        
        {currentView === 'dashboard' && (
          <Dashboard 
            onCreate={handleCreatePackage}
            onEdit={handleEditPackage}
            onDuplicate={handleDuplicatePackage}
          />
        )}

        {currentView === 'form' && (
          <PackageForm 
            initialData={editingPackage}
            onSave={handleSavePackage}
            onCancel={() => setCurrentView('dashboard')}
            isReadOnlyForm={!canEditPackage && !canCreatePackage} 
            canSaveDraft={canSaveDraft}
            canPublishPackage={canPublishPackage}
          />
        )}

        {currentView === 'users' && canViewUsers && (
            <UserManagement />
        )}

        {currentView === 'sales' && canViewSales && (
            <SalesManagement onAddBooking={handleAddBooking} />
        )}

        {currentView === 'voyages' && (
            <VoyageList 
                onBook={(pkg) => {
                    if (role === 'administrator' || role === 'sales_agent') {
                        setCurrentView('sales');
                        alert("Veuillez créer une nouvelle réservation dans l'onglet Ventes pour " + pkg.general.productName);
                    } else {
                        alert("Contactez un agent commercial pour réserver : " + pkg.general.productName);
                    }
                }}
            />
        )}

        {currentView === 'ops' && canViewOps && (
            selectedOpsGroup ? (
                <OpsManager 
                    pkg={selectedOpsGroup.pkg}
                    opsGroup={selectedOpsGroup.group}
                    onBack={() => setSelectedOpsGroup(null)}
                />
            ) : (
                <OpsDashboard 
                    onSelectGroup={(pkg, group) => setSelectedOpsGroup({pkg, group})}
                />
            )
        )}

      </main>
    </div>
  );
}